/* Generated By:JavaCC: Do not edit this line. ProjLangParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ProjLangParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IF = 5;
  /** RegularExpression Id. */
  int THEN = 6;
  /** RegularExpression Id. */
  int ELSE = 7;
  /** RegularExpression Id. */
  int WHILE = 8;
  /** RegularExpression Id. */
  int DO = 9;
  /** RegularExpression Id. */
  int LET = 10;
  /** RegularExpression Id. */
  int FUN = 11;
  /** RegularExpression Id. */
  int VAL = 12;
  /** RegularExpression Id. */
  int IN = 13;
  /** RegularExpression Id. */
  int END = 14;
  /** RegularExpression Id. */
  int TRUE = 15;
  /** RegularExpression Id. */
  int FALSE = 16;
  /** RegularExpression Id. */
  int ID = 17;
  /** RegularExpression Id. */
  int NUM = 18;
  /** RegularExpression Id. */
  int ASSIGN = 19;
  /** RegularExpression Id. */
  int MUL = 20;
  /** RegularExpression Id. */
  int DIV = 21;
  /** RegularExpression Id. */
  int AND = 22;
  /** RegularExpression Id. */
  int ADD = 23;
  /** RegularExpression Id. */
  int SUB = 24;
  /** RegularExpression Id. */
  int OR = 25;
  /** RegularExpression Id. */
  int EQUAL = 26;
  /** RegularExpression Id. */
  int LESS = 27;
  /** RegularExpression Id. */
  int NEG = 28;
  /** RegularExpression Id. */
  int SEMI = 29;
  /** RegularExpression Id. */
  int LBRACKET = 30;
  /** RegularExpression Id. */
  int RBRACKET = 31;
  /** RegularExpression Id. */
  int LPAR = 32;
  /** RegularExpression Id. */
  int RPAR = 33;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"while\"",
    "\"do\"",
    "\"let\"",
    "\"fun\"",
    "\"val\"",
    "\"in\"",
    "\"end\"",
    "\"true\"",
    "\"false\"",
    "<ID>",
    "<NUM>",
    "\":=\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"+\"",
    "\"-\"",
    "\"|\"",
    "\"=\"",
    "\"<\"",
    "\"!\"",
    "\";\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
  };

}
